#!/bin/sh
# Name : Dolce
# Date : 1 March 2021
# Description : dolce is a hacking tools installer and package manager for hacker's.

logo="

██████╗░░█████╗░██╗░░░░░░█████╗░███████╗
██╔══██╗██╔══██╗██║░░░░░██╔══██╗██╔════╝
██║░░██║██║░░██║██║░░░░░██║░░╚═╝█████╗░░
██║░░██║██║░░██║██║░░░░░██║░░██╗██╔══╝░░
██████╔╝╚█████╔╝███████╗╚█████╔╝███████╗
╚═════╝░░╚════╝░╚══════╝░╚════╝░╚══════╝

"

# checking for system home dir
if [ -d $HOME ]; then
  home=$HOME
else
  home="~/"
fi

# checking for system bin dir
if [ -d /data/data/com.termux/files/usr/bin ]; then
  bin="/data/data/com.termux/files/usr/bin"
elif [ -d /usr/local/bin ]; then
  bin="/usr/local/bin"
elif [ -d /bin ]; then
  bin="/bin"
elif [ -d /sbin ]; then
  bin="/sbin"
fi

# checking for configuration dir
if [ -d /data/data/com.termux/files/usr/etc ]; then
  conf_dir="/data/data/com.termux/files/usr/etc"
elif [ -d /etc ]; then
  conf_dir="/etc"
fi

# configuration files
if [ -d $conf_dir/dolce ]; then
  if [ -e $conf_dir/dolce/data/tools.dat ]; then
    tools_data="$conf_dir/dolce/data/tools.dat"
  fi
  if [ -e $conf_dir/dolce/data/category.dat ]; then
    category_data="$conf_dir/dolce/data/category.dat"
  fi
else
  if [ -e data/tools.dat ]; then
    tools_data="data/tools.dat"
  fi
  if [ -e data/category.dat ]; then
    category_data="data/category.dat"
  fi
fi

# checking for system root access
if [ -e /usr/lib/sudo ]; then
  sudo="sudo"
elif [ -e /usr/bin/sudo ]; then
  sudo="sudo"
elif [ -e /usr/sbin/sudo ]; then
  sudo="sudo"
elif [ -e /lib/sudo ]; then
  sudo="sudo"
elif [ -e /bin/sudo ]; then
  sudo="sudo"
elif [ -e /sbin/sudo ]; then
  sudo="sudo"
elif [ -e /data/data/com.termux/files/usr/bin/sudo ]; then
  sudo="sudo"
else
  sudo=""
fi

# checking for system package manager
if [ -e /bin/apt ]; then
  pac="apt-get"
  system="linux"
elif [ -e /bin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /usr/bin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /sbin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /usr/sbin/apt-get ]; then
  pac="apt-get"
  system="linux"
elif [ -e /bin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /usr/bin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /sbin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /usr/sbin/apk ]; then
  pac="apk"
  system="linux"
elif [ -e /bin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/bin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /sbin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/sbin/yum ]; then
  pac="yum"
  system="fedora"
elif [ -e /usr/local/bin/brew ]; then
  pac="brew"
  system="mac"
  sudo=""
elif [ -e /data/data/com.termux/files/usr/bin/pkg ]; then
  pac="pkg"
  system="termux"
elif [ -e /data/data/com.termux/files/usr/bin/apt ]; then
  pac="apt"
  system="termux"
elif [ -e /data/data/com.termux/files/usr/bin/apt-get ]; then
  pac="apt-get"
  system="termux"
fi

# setup process
clear
echo "$logo"
echo "#-Installing .... "
sleep 1
echo "#-Running setup .... "
sleep 1

# installing dependency
if [ ! -e $bin/wget ]; then
  if [ $sudo ]; then
    $sudo $pac install wget -y
  else
    $pac install wget -y
  fi
fi
if [ ! -e $bin/curl ]; then
  if [ $sudo ]; then
    $sudo $pac install curl -y
  else
    $pac install curl -y
  fi
fi
if [ ! -e $bin/git ]; then
  if [ $sudo ]; then
    $sudo $pac install git -y
  else
    $pac install git -y
  fi
fi

# removing old one
if [ -e $bin/dolce ]; then
  if [ -d $conf_dir/dolce ]; then
    if [ $sudo ]; then
      $sudo rm -rf $bin/dolce
      $sudo rm -rf $conf_dir/dolce
    else
      rm -rf $bin/dolce
      rm -rf $conf_dir/dolce
    fi
  fi
fi

# install dolce
if [ $0 = "install" -o $0 = "./install" ]; then
  if [ -e dolce ]; then
    if [ $sudo ]; then
      $sudo mv -v dolce $bin
      $sudo chmod +x $bin/dolce
    else
      mv -v dolce $bin
      chmod +x $bin/dolce
    fi
  fi
  cd ..
  if [ -d dolce ]; then
    if [ $sudo ]; then
    $sudo mv -v dolce $conf_dir
    else
      mv -v dolce $conf_dir
    fi
  fi
else
  if [ -e dolce/dolce ]; then
    if [ $sudo ]; then
      $sudo mv -v dolce/dolce $bin
      $sudo chmod +x $bin/dolce
    else
      mv -v dolce/dolce $bin
      chmod +x $bin/dolce
    fi
  fi
  if [ -d dolce ]; then
    if [ $sudo ]; then
    $sudo mv -v dolce $conf_dir
    else
      mv -v dolce $conf_dir
    fi
  fi
fi

# check dolce is installed or not
if [ -e $bin/dolce ]; then
  if [ -d $conf_dir/dolce ]; then
    clear
    echo "$logo"
    echo " Doolce Library Installed Successfully !!"
    echo " type [dolce -h] For Help."
  else
    clear
    echo "$logo"
    echo "Sorry Dolce Library Is Not Installed !!"
    echo "Please Try Again"
  fi
fi
